### ISSUE TITLE
py_spec installation is borken

### ISSUE THREAD

**Issue by abaillod** [PrincetonUniversity/SPEC#194]
Hi,

It seems that py_spec is broken:
```
❯ pip install py_spec                                   
Collecting py_spec
  Downloading py_spec-3.3.2-py3-none-any.whl (23 kB)
Installing collected packages: py_spec
Successfully installed py_spec-3.3.2
(base) 
~ 
❯ python                           
Python 3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import py_spec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/py_spec/__init__.py", line 4, in <module>
    from .ci import test
ModuleNotFoundError: No module named 'py_spec.ci'
```

**Comment by smiet** [comment]
This is fixed by #195, which now includes the missing import in the pip distribution. 

I made the choice to include it as accessing the functions in `.ci` is useful for developers who want to run the compare script in `py_spec.ci` when preparing a new merge into master.
